Repository JohnnyIrvin/shell-craft, pull requests merged in 2023-03, with the labels that each got.

#1 How to install plus acknowledgements
  README.md
Labels: documentation

#2 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#3 Github Action - Publish Python distribution.
  .github/workflows/package-publish.yml
  .gitignore
  README.md
  ai.py
  pyproject.toml
  shell_craft/__init__.py
  shell_craft/__main__.py
  shell_craft/cli.py
  shell_craft/service.py
Labels: enhancement

#4 Rename project for pypi.
  README.md
  pyproject.toml
Labels: bug

#5 Add PyPI version badge and link
  README.md
Labels: enhancement

#11 Update Package Publish - Remove PyPi testing deployment.
  .github/workflows/package-publish.yml
Labels: bug

#10 Update README - Acknowledgments
  README.md
Labels: documentation

#30 Accept STDIN as input
  shell_craft/cli.py
Labels: enhancement

#32 Update PackPublish - If at job level
  .github/workflows/package-publish.yml
Labels: bug

#33 Update licensing - include contributors
  LICENSE
  shell_craft/__main__.py
  shell_craft/cli.py
  shell_craft/factories/__init__.py
  shell_craft/factories/prompt.py
  shell_craft/prompts/__init__.py
  shell_craft/prompts/feature_request.py
  shell_craft/prompts/languages.py
  shell_craft/prompts/prompt.py
  shell_craft/service.py
  tests/test_factories.py
Labels: documentation

#39 Update reference to `Service` in API example
  README.md
Labels: documentation

#40 Upgrade README
  README.md
Labels: documentation

#50 update README.md to describe new features
  README.md
Labels: documentation
