Repository JohnnyIrvin/shell-craft, pull requests merged in 2023-04, with the labels that each got.

#57 pull config from more standard places (XDG_CONFIG_HOME/shell-craft)
  README.md
  shell_craft/cli/key.py
Labels: documentation, enhancement

#61 fix(release): Update semver workflow, forgot arg
  .github/workflows/semver-bump.yml
Labels: bug

#62 fix(release): Missing evaluation for changelog
  .github/workflows/semver-bump.yml
Labels: bug

#63 feat(release): Update release action
  .github/workflows/semver-bump.yml
Labels: enhancement

#64 bug(release): Add release permissions
  .github/workflows/semver-bump.yml
Labels: bug

#65 fix(release): Semvar ifs not evaluating
  .github/workflows/semver-bump.yml
Labels: bug

#67 fix(cli): ValueError prints help for api-key
  shell_craft/cli/key.py
Labels: bug

#70 fix(prompt): System messages replaced with user messages.
  shell_craft/prompts/prompt.py
Labels: bug

#75 CLI Features, number of prompts and temperature
  shell_craft/cli/main.py
  shell_craft/cli/results.py
  shell_craft/service.py
Labels: enhancement
